### 配置网关反向代理
zuul:
  routes:
    api-a:
     ### 以 /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: SpringCloud-zuul-member
    api-b:
        ### 以 /api-order/访问转发到订单服务
      path: /api-order/**
      serviceId: SpringCloud-zuul-order
    api-c:
        ### 以 /api-order/访问转发到订单服务
      path: /api-zuul/**
      serviceId: SpringCloud-zuul
      
apptests: nihao
